name: Node.js CI - Unit test - web frontend

env: 
  NODE_ENV: ${{secrets.NODE_ENV}}
  SERVER_URL: ${{secrets.SERVER_URL}}
  ADMIN_SERVER_URL: ${{secrets.ADMIN_SERVER_URL}}
  NEXT_PUBLIC_DOMAIN: ${{secrets.NEXT_PUBLIC_DOMAIN}}
  NEXT_PUBLIC_ALGOLIA_APP_ID: ${{secrets.NEXT_PUBLIC_ALGOLIA_APP_ID}}
  NEXT_PUBLIC_ALGOLIA_SEARCH_KEY: ${{secrets.NEXT_PUBLIC_ALGOLIA_SEARCH_KEY}}
  NEXT_PUBLIC_FIREBASE_TEMPLATE_IMAGE_LINK: ${{secrets.NEXT_PUBLIC_FIREBASE_TEMPLATE_IMAGE_LINK}}
  NEXT_PUBLIC_API_KEY: ${{secrets.NEXT_PUBLIC_API_KEY}}
  NEXT_PUBLIC_AUTH_DOMAIN: ${{secrets.NEXT_PUBLIC_AUTH_DOMAIN}}
  NEXT_PUBLIC_PROJECT_ID: ${{secrets.NEXT_PUBLIC_PROJECT_ID}}
  NEXT_PUBLIC_STORAGE_BUCKET: ${{secrets.NEXT_PUBLIC_STORAGE_BUCKET}}
  NEXT_PUBLIC_MESSAGING_SENDER_ID: ${{secrets.NEXT_PUBLIC_MESSAGING_SENDER_ID}}
  NEXT_PUBLIC_APP_ID: ${{secrets.NEXT_PUBLIC_APP_ID}}
  NEXT_PUBLIC_MEASUREMENT_ID: ${{secrets.NEXT_PUBLIC_MEASUREMENT_ID}}

on:
  push:
    branches: [ "develop" ]
    paths:
      - "client/web/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client/web
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: "pnpm"
          cache-dependency-path: client/web/pnpm-lock.yaml
      
      - name: Install dependencies
        run: pnpm install
      - name: Unit test
        run: pnpm run test
